import type { RoadmapModuleDef } from "../types";

export const PRACTICE_ROADMAP: readonly RoadmapModuleDef[] = [
  {
    id: "foundations",
    title: "Foundations",
    description: "Build fluency with core programming and problem-solving tools.",
    topicAliases: [
      "Basics",
      "Fundamentals",
      "Implementation",
      "Math",
      "Mathematics",
      "Bit Manipulation",
      "Bitwise",
      "Hashing",
      "Hash Map",
      "HashMap",
      "Hash Table",
      "Set",
    ],
  },
  {
    id: "arrays",
    title: "Arrays",
    description: "Master traversal, prefix techniques, and array patterns.",
    topicAliases: [
      "Array",
      "Arrays",
      "Matrix",
      "Prefix Sum",
      "Two Pointers",
      "Sliding Window",
    ],
  },
  {
    id: "searching",
    title: "Searching",
    description: "Locate answers efficiently with linear and binary search.",
    topicAliases: [
      "Search",
      "Searching",
      "Binary Search",
      "Linear Search",
      "Ternary Search",
    ],
  },
  {
    id: "sorting",
    title: "Sorting",
    description: "Order data and learn comparison and partitioning strategies.",
    topicAliases: [
      "Sort",
      "Sorting",
      "Merge Sort",
      "Quick Sort",
      "Counting Sort",
      "Heap Sort",
    ],
  },
  {
    id: "strings",
    title: "Strings",
    description: "Work with text, matching, parsing, and character patterns.",
    topicAliases: [
      "String",
      "Strings",
      "String Matching",
      "Trie",
      "Prefix Tree",
    ],
  },
  {
    id: "linked-list",
    title: "Linked List",
    description: "Practice pointer manipulation and linked data structures.",
    topicAliases: [
      "Linked List",
      "Linked Lists",
      "Singly Linked List",
      "Doubly Linked List",
    ],
  },
  {
    id: "stack-queue",
    title: "Stack & Queue",
    description: "Use ordered access patterns to model state and processing.",
    topicAliases: [
      "Stack",
      "Stacks",
      "Queue",
      "Queues",
      "Deque",
      "Monotonic Stack",
      "Monotonic Queue",
      "Priority Queue",
      "Heap",
    ],
  },
  {
    id: "trees",
    title: "Trees",
    description: "Traverse and reason about hierarchical data structures.",
    topicAliases: [
      "Tree",
      "Trees",
      "Binary Tree",
      "Binary Search Tree",
      "BST",
      "Segment Tree",
      "Fenwick Tree",
    ],
  },
  {
    id: "graphs",
    title: "Graphs",
    description: "Explore connectivity, traversal, and shortest-path problems.",
    topicAliases: [
      "Graph",
      "Graphs",
      "Graph Theory",
      "BFS",
      "Breadth First Search",
      "DFS",
      "Depth First Search",
      "Shortest Path",
      "Dijkstra",
      "Topological Sort",
      "Union Find",
      "Disjoint Set",
    ],
  },
  {
    id: "greedy",
    title: "Greedy",
    description: "Make locally optimal choices and prove when they work.",
    topicAliases: ["Greedy", "Greedy Algorithm", "Greedy Algorithms"],
  },
  {
    id: "backtracking",
    title: "Backtracking",
    description: "Search solution spaces with pruning and reversible choices.",
    topicAliases: [
      "Backtracking",
      "Recursion",
      "Divide and Conquer",
      "Branch and Bound",
    ],
  },
  {
    id: "dynamic-programming",
    title: "Dynamic Programming",
    description: "Solve overlapping subproblems with memoization and tabulation.",
    topicAliases: [
      "DP",
      "Dynamic Programming",
      "Memoization",
      "Tabulation",
      "Knapsack",
    ],
  },
  {
    id: "other",
    title: "Other",
    description: "Explore problems outside the core curriculum tracks.",
    topicAliases: [],
  },
] as const;

export const OTHER_MODULE_ID = "other";
