import type { LessonSection } from "../types";

export const PROVING_GROUNDS_SECTION: LessonSection = {
  id: "proving-grounds",
  title: "The Proving Grounds",
  subtitle:
    "20 classic problems every programmer solves once — sharpen the fundamentals before moving on.",
  lessons: [
    {
      slug: "sum-and-percentage-of-marks",
      order: 1,
      title: "Sum and Percentage of Marks",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 121,
      teaser: "Read five subject marks, then print their sum and percentage.",
      blocks: [],
    },
    {
      slug: "simple-and-compound-interest",
      order: 2,
      title: "Simple and Compound Interest",
      estMinutes: 15,
      kind: "solve",
      linkedProblemId: 122,
      teaser: "From principal, rate, and time, compute both simple and compound interest.",
      blocks: [],
    },
    {
      slug: "area-and-circumference-of-circle",
      order: 3,
      title: "Area and Circumference of a Circle",
      estMinutes: 10,
      kind: "solve",
      linkedProblemId: 123,
      teaser: "Given a radius, print the circle’s area and circumference.",
      blocks: [],
    },
    {
      slug: "celsius-to-fahrenheit",
      order: 4,
      title: "Celsius to Fahrenheit",
      estMinutes: 8,
      kind: "solve",
      linkedProblemId: 124,
      teaser: "Convert a Celsius temperature to Fahrenheit.",
      blocks: [],
    },
    {
      slug: "swap-two-numbers",
      order: 5,
      title: "Swap Two Numbers",
      estMinutes: 8,
      kind: "solve",
      linkedProblemId: 125,
      teaser: "Swap two numbers using a third variable, then print both.",
      blocks: [],
    },
    {
      slug: "check-numbers-equal",
      order: 6,
      title: "Check Numbers Equal",
      estMinutes: 8,
      kind: "solve",
      linkedProblemId: 126,
      teaser: "Decide whether two numbers are equal.",
      blocks: [],
    },
    {
      slug: "greatest-of-three-numbers",
      order: 7,
      title: "Greatest of Three Numbers",
      estMinutes: 10,
      kind: "solve",
      linkedProblemId: 127,
      teaser: "Find the greatest among three integers.",
      blocks: [],
    },
    {
      slug: "even-or-odd",
      order: 8,
      title: "Even or Odd",
      estMinutes: 8,
      kind: "solve",
      linkedProblemId: 128,
      teaser: "Say whether a number is even or odd.",
      blocks: [],
    },
    {
      slug: "leap-year-check",
      order: 9,
      title: "Leap Year Check",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 129,
      teaser: "Decide if a year is a leap year using the full calendar rules.",
      blocks: [],
    },
    {
      slug: "grade-calculator",
      order: 10,
      title: "Grade Calculator",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 130,
      teaser: "Map a percentage to letter grades A–D with clear boundaries.",
      blocks: [],
    },
    {
      slug: "calculator-using-switch",
      order: 11,
      title: "Calculator Using Switch",
      estMinutes: 15,
      kind: "solve",
      linkedProblemId: 131,
      teaser: "Take two operands and an operator; use a switch to compute the result.",
      blocks: [],
    },
    {
      slug: "sum-of-n-numbers",
      order: 12,
      title: "Sum of N Numbers",
      estMinutes: 10,
      kind: "solve",
      linkedProblemId: 132,
      teaser: "Sum all integers from 1 to N.",
      blocks: [],
    },
    {
      slug: "factorial-of-a-number",
      order: 13,
      title: "Factorial of a Number",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 133,
      teaser: "Compute N! for a non-negative integer N.",
      blocks: [],
    },
    {
      slug: "sum-of-even-and-odd-numbers",
      order: 14,
      title: "Sum of Even and Odd Numbers",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 134,
      teaser: "From 1 to N, print the sum of evens and the sum of odds separately.",
      blocks: [],
    },
    {
      slug: "fibonacci-series",
      order: 15,
      title: "Fibonacci Series",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 135,
      teaser: "Print the first N terms of the Fibonacci series.",
      blocks: [],
    },
    {
      slug: "prime-number-check",
      order: 16,
      title: "Prime Number Check",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 136,
      teaser: "Decide whether a number is prime (watch 0, 1, and 2).",
      blocks: [],
    },
    {
      slug: "sum-of-digits",
      order: 17,
      title: "Sum of Digits",
      estMinutes: 10,
      kind: "solve",
      linkedProblemId: 137,
      teaser: "Add up every digit of an entered number.",
      blocks: [],
    },
    {
      slug: "reverse-a-number",
      order: 18,
      title: "Reverse a Number",
      estMinutes: 12,
      kind: "solve",
      linkedProblemId: 138,
      teaser: "Print the reverse of an integer (trailing zeros disappear as digits).",
      blocks: [],
    },
    {
      slug: "armstrong-numbers",
      order: 19,
      title: "Armstrong Numbers",
      estMinutes: 18,
      kind: "solve",
      linkedProblemId: 139,
      teaser: "Print all Armstrong numbers from 1 to 1000.",
      blocks: [],
    },
    {
      slug: "binary-decimal-conversion",
      order: 20,
      title: "Binary–Decimal Conversion",
      estMinutes: 18,
      kind: "solve",
      linkedProblemId: 140,
      teaser: "Convert both ways: binary string to decimal, and decimal to binary.",
      blocks: [],
    },
  ],
};
